// This file is auto-generated by Lovable. Do not modify it.

// Lovable auth integration removed for standalone auth flows.
// This module is intentionally left as a stub to avoid build-time failures
// if any legacy imports still exist.

export const lovable = {
  auth: {
    signInWithOAuth: async () => {
      throw new Error("Lovable auth was removed. Use supabase.auth.signInWithOAuth instead.");
    },
  },
};

