/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWeatherRouteImport } from './routes/_authenticated/app.weather'
import { Route as AuthenticatedAppTripsRouteImport } from './routes/_authenticated/app.trips'
import { Route as AuthenticatedAppSurvivalRouteImport } from './routes/_authenticated/app.survival'
import { Route as AuthenticatedAppStoryRouteImport } from './routes/_authenticated/app.story'
import { Route as AuthenticatedAppSimilarRouteImport } from './routes/_authenticated/app.similar'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppScoreRouteImport } from './routes/_authenticated/app.score'
import { Route as AuthenticatedAppSafetyRouteImport } from './routes/_authenticated/app.safety'
import { Route as AuthenticatedAppRoutesRouteImport } from './routes/_authenticated/app.routes'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppPlanRouteImport } from './routes/_authenticated/app.plan'
import { Route as AuthenticatedAppNowRouteImport } from './routes/_authenticated/app.now'
import { Route as AuthenticatedAppNearbyRouteImport } from './routes/_authenticated/app.nearby'
import { Route as AuthenticatedAppMemoryRouteImport } from './routes/_authenticated/app.memory'
import { Route as AuthenticatedAppInsightsRouteImport } from './routes/_authenticated/app.insights'
import { Route as AuthenticatedAppGemsRouteImport } from './routes/_authenticated/app.gems'
import { Route as AuthenticatedAppDiscoverRouteImport } from './routes/_authenticated/app.discover'
import { Route as AuthenticatedAppCrowdRouteImport } from './routes/_authenticated/app.crowd'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppBudgetRouteImport } from './routes/_authenticated/app.budget'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWeatherRoute = AuthenticatedAppWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTripsRoute = AuthenticatedAppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSurvivalRoute =
  AuthenticatedAppSurvivalRouteImport.update({
    id: '/survival',
    path: '/survival',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppStoryRoute = AuthenticatedAppStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSimilarRoute = AuthenticatedAppSimilarRouteImport.update({
  id: '/similar',
  path: '/similar',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppScoreRoute = AuthenticatedAppScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSafetyRoute = AuthenticatedAppSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRoutesRoute = AuthenticatedAppRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPlanRoute = AuthenticatedAppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNowRoute = AuthenticatedAppNowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNearbyRoute = AuthenticatedAppNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMemoryRoute = AuthenticatedAppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInsightsRoute =
  AuthenticatedAppInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGemsRoute = AuthenticatedAppGemsRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDiscoverRoute =
  AuthenticatedAppDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCrowdRoute = AuthenticatedAppCrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBudgetRoute = AuthenticatedAppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/modules': typeof ModulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/budget': typeof AuthenticatedAppBudgetRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/crowd': typeof AuthenticatedAppCrowdRoute
  '/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/app/gems': typeof AuthenticatedAppGemsRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/memory': typeof AuthenticatedAppMemoryRoute
  '/app/nearby': typeof AuthenticatedAppNearbyRoute
  '/app/now': typeof AuthenticatedAppNowRoute
  '/app/plan': typeof AuthenticatedAppPlanRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/routes': typeof AuthenticatedAppRoutesRoute
  '/app/safety': typeof AuthenticatedAppSafetyRoute
  '/app/score': typeof AuthenticatedAppScoreRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/similar': typeof AuthenticatedAppSimilarRoute
  '/app/story': typeof AuthenticatedAppStoryRoute
  '/app/survival': typeof AuthenticatedAppSurvivalRoute
  '/app/trips': typeof AuthenticatedAppTripsRoute
  '/app/weather': typeof AuthenticatedAppWeatherRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/modules': typeof ModulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/budget': typeof AuthenticatedAppBudgetRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/crowd': typeof AuthenticatedAppCrowdRoute
  '/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/app/gems': typeof AuthenticatedAppGemsRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/memory': typeof AuthenticatedAppMemoryRoute
  '/app/nearby': typeof AuthenticatedAppNearbyRoute
  '/app/now': typeof AuthenticatedAppNowRoute
  '/app/plan': typeof AuthenticatedAppPlanRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/routes': typeof AuthenticatedAppRoutesRoute
  '/app/safety': typeof AuthenticatedAppSafetyRoute
  '/app/score': typeof AuthenticatedAppScoreRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/similar': typeof AuthenticatedAppSimilarRoute
  '/app/story': typeof AuthenticatedAppStoryRoute
  '/app/survival': typeof AuthenticatedAppSurvivalRoute
  '/app/trips': typeof AuthenticatedAppTripsRoute
  '/app/weather': typeof AuthenticatedAppWeatherRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/modules': typeof ModulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/budget': typeof AuthenticatedAppBudgetRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/crowd': typeof AuthenticatedAppCrowdRoute
  '/_authenticated/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/_authenticated/app/gems': typeof AuthenticatedAppGemsRoute
  '/_authenticated/app/insights': typeof AuthenticatedAppInsightsRoute
  '/_authenticated/app/memory': typeof AuthenticatedAppMemoryRoute
  '/_authenticated/app/nearby': typeof AuthenticatedAppNearbyRoute
  '/_authenticated/app/now': typeof AuthenticatedAppNowRoute
  '/_authenticated/app/plan': typeof AuthenticatedAppPlanRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/routes': typeof AuthenticatedAppRoutesRoute
  '/_authenticated/app/safety': typeof AuthenticatedAppSafetyRoute
  '/_authenticated/app/score': typeof AuthenticatedAppScoreRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/similar': typeof AuthenticatedAppSimilarRoute
  '/_authenticated/app/story': typeof AuthenticatedAppStoryRoute
  '/_authenticated/app/survival': typeof AuthenticatedAppSurvivalRoute
  '/_authenticated/app/trips': typeof AuthenticatedAppTripsRoute
  '/_authenticated/app/weather': typeof AuthenticatedAppWeatherRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/features'
    | '/modules'
    | '/sitemap.xml'
    | '/app'
    | '/app/budget'
    | '/app/chat'
    | '/app/crowd'
    | '/app/discover'
    | '/app/gems'
    | '/app/insights'
    | '/app/memory'
    | '/app/nearby'
    | '/app/now'
    | '/app/plan'
    | '/app/profile'
    | '/app/routes'
    | '/app/safety'
    | '/app/score'
    | '/app/settings'
    | '/app/similar'
    | '/app/story'
    | '/app/survival'
    | '/app/trips'
    | '/app/weather'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/features'
    | '/modules'
    | '/sitemap.xml'
    | '/app/budget'
    | '/app/chat'
    | '/app/crowd'
    | '/app/discover'
    | '/app/gems'
    | '/app/insights'
    | '/app/memory'
    | '/app/nearby'
    | '/app/now'
    | '/app/plan'
    | '/app/profile'
    | '/app/routes'
    | '/app/safety'
    | '/app/score'
    | '/app/settings'
    | '/app/similar'
    | '/app/story'
    | '/app/survival'
    | '/app/trips'
    | '/app/weather'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/features'
    | '/modules'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/app/budget'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/crowd'
    | '/_authenticated/app/discover'
    | '/_authenticated/app/gems'
    | '/_authenticated/app/insights'
    | '/_authenticated/app/memory'
    | '/_authenticated/app/nearby'
    | '/_authenticated/app/now'
    | '/_authenticated/app/plan'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/routes'
    | '/_authenticated/app/safety'
    | '/_authenticated/app/score'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/similar'
    | '/_authenticated/app/story'
    | '/_authenticated/app/survival'
    | '/_authenticated/app/trips'
    | '/_authenticated/app/weather'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRoute
  ModulesRoute: typeof ModulesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/weather': {
      id: '/_authenticated/app/weather'
      path: '/weather'
      fullPath: '/app/weather'
      preLoaderRoute: typeof AuthenticatedAppWeatherRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trips': {
      id: '/_authenticated/app/trips'
      path: '/trips'
      fullPath: '/app/trips'
      preLoaderRoute: typeof AuthenticatedAppTripsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/survival': {
      id: '/_authenticated/app/survival'
      path: '/survival'
      fullPath: '/app/survival'
      preLoaderRoute: typeof AuthenticatedAppSurvivalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/story': {
      id: '/_authenticated/app/story'
      path: '/story'
      fullPath: '/app/story'
      preLoaderRoute: typeof AuthenticatedAppStoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/similar': {
      id: '/_authenticated/app/similar'
      path: '/similar'
      fullPath: '/app/similar'
      preLoaderRoute: typeof AuthenticatedAppSimilarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/score': {
      id: '/_authenticated/app/score'
      path: '/score'
      fullPath: '/app/score'
      preLoaderRoute: typeof AuthenticatedAppScoreRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/safety': {
      id: '/_authenticated/app/safety'
      path: '/safety'
      fullPath: '/app/safety'
      preLoaderRoute: typeof AuthenticatedAppSafetyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/routes': {
      id: '/_authenticated/app/routes'
      path: '/routes'
      fullPath: '/app/routes'
      preLoaderRoute: typeof AuthenticatedAppRoutesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/plan': {
      id: '/_authenticated/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AuthenticatedAppPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/now': {
      id: '/_authenticated/app/now'
      path: '/now'
      fullPath: '/app/now'
      preLoaderRoute: typeof AuthenticatedAppNowRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/nearby': {
      id: '/_authenticated/app/nearby'
      path: '/nearby'
      fullPath: '/app/nearby'
      preLoaderRoute: typeof AuthenticatedAppNearbyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/memory': {
      id: '/_authenticated/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AuthenticatedAppMemoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/insights': {
      id: '/_authenticated/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AuthenticatedAppInsightsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/gems': {
      id: '/_authenticated/app/gems'
      path: '/gems'
      fullPath: '/app/gems'
      preLoaderRoute: typeof AuthenticatedAppGemsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/discover': {
      id: '/_authenticated/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AuthenticatedAppDiscoverRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/crowd': {
      id: '/_authenticated/app/crowd'
      path: '/crowd'
      fullPath: '/app/crowd'
      preLoaderRoute: typeof AuthenticatedAppCrowdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/budget': {
      id: '/_authenticated/app/budget'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AuthenticatedAppBudgetRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBudgetRoute: typeof AuthenticatedAppBudgetRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppCrowdRoute: typeof AuthenticatedAppCrowdRoute
  AuthenticatedAppDiscoverRoute: typeof AuthenticatedAppDiscoverRoute
  AuthenticatedAppGemsRoute: typeof AuthenticatedAppGemsRoute
  AuthenticatedAppInsightsRoute: typeof AuthenticatedAppInsightsRoute
  AuthenticatedAppMemoryRoute: typeof AuthenticatedAppMemoryRoute
  AuthenticatedAppNearbyRoute: typeof AuthenticatedAppNearbyRoute
  AuthenticatedAppNowRoute: typeof AuthenticatedAppNowRoute
  AuthenticatedAppPlanRoute: typeof AuthenticatedAppPlanRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppRoutesRoute: typeof AuthenticatedAppRoutesRoute
  AuthenticatedAppSafetyRoute: typeof AuthenticatedAppSafetyRoute
  AuthenticatedAppScoreRoute: typeof AuthenticatedAppScoreRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSimilarRoute: typeof AuthenticatedAppSimilarRoute
  AuthenticatedAppStoryRoute: typeof AuthenticatedAppStoryRoute
  AuthenticatedAppSurvivalRoute: typeof AuthenticatedAppSurvivalRoute
  AuthenticatedAppTripsRoute: typeof AuthenticatedAppTripsRoute
  AuthenticatedAppWeatherRoute: typeof AuthenticatedAppWeatherRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBudgetRoute: AuthenticatedAppBudgetRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppCrowdRoute: AuthenticatedAppCrowdRoute,
  AuthenticatedAppDiscoverRoute: AuthenticatedAppDiscoverRoute,
  AuthenticatedAppGemsRoute: AuthenticatedAppGemsRoute,
  AuthenticatedAppInsightsRoute: AuthenticatedAppInsightsRoute,
  AuthenticatedAppMemoryRoute: AuthenticatedAppMemoryRoute,
  AuthenticatedAppNearbyRoute: AuthenticatedAppNearbyRoute,
  AuthenticatedAppNowRoute: AuthenticatedAppNowRoute,
  AuthenticatedAppPlanRoute: AuthenticatedAppPlanRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppRoutesRoute: AuthenticatedAppRoutesRoute,
  AuthenticatedAppSafetyRoute: AuthenticatedAppSafetyRoute,
  AuthenticatedAppScoreRoute: AuthenticatedAppScoreRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSimilarRoute: AuthenticatedAppSimilarRoute,
  AuthenticatedAppStoryRoute: AuthenticatedAppStoryRoute,
  AuthenticatedAppSurvivalRoute: AuthenticatedAppSurvivalRoute,
  AuthenticatedAppTripsRoute: AuthenticatedAppTripsRoute,
  AuthenticatedAppWeatherRoute: AuthenticatedAppWeatherRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRoute,
  ModulesRoute: ModulesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
